name: Notify Mattermost on Issue, Discussion, or Comment

on:
  issues:
    types: [opened] # 이슈 생성 이벤트
  discussion:
    types: [created] # 글 작성 이벤트
  issue_comment:
    types: [created] # 이슈에 댓글 생성 이벤트

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Send Notification to Mattermost
      env:
        MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }} # 시크릿에 저장한 웹훅 URL
      run: |
        # Determine event type and build the message dynamically
        if [[ "${{ github.event_name }}" == "issues" ]]; then
          MESSAGE="**New Issue Created**\n\n**Repository:** ${{ github.repository }}\n**Title:** ${{ github.event.issue.title }}\n**URL:** ${{ github.event.issue.html_url }}"
        elif [[ "${{ github.event_name }}" == "discussion" ]]; then
          MESSAGE="**New Discussion Created**\n\n**Repository:** ${{ github.repository }}\n**Title:** ${{ github.event.discussion.title }}\n**URL:** ${{ github.event.discussion.html_url }}"
        elif [[ "${{ github.event_name }}" == "issue_comment" ]]; then
          MESSAGE="**New Comment on Issue**\n\n**Repository:** ${{ github.repository }}\n**Issue Title:** ${{ github.event.issue.title }}\n**Comment:** ${{ github.event.comment.body }}\n**Comment URL:** ${{ github.event.comment.html_url }}"
        fi

        curl -X POST -H 'Content-Type: application/json' \
          -d "{
                \"text\": \"$MESSAGE\"
              }" \
          $MATTERMOST_WEBHOOK_URL
